- {{ cookiecutter.package_name|slugify }}/pyproject.toml
> Add `--failed-first` to pytest

- {{ cookiecutter.package_name|slugify }}/Dockerfile
> Install specific Poetry version

- README.md
- {{ cookiecutter.package_name|slugify }}/Dockerfile
> feat: add support for verified commits

- hooks/post_gen_project.py
Jinja expression could evaluate to an int instead of a bool, this PR fixes that.
> fix: fix jinja expression

- {{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
> feat: configure black's python version

- .github/workflows/test.yml
- {{ cookiecutter.__package_name_kebab_case }}/.pre-commit-config.yaml
> feat: add meta pre-commit hooks

- {{ cookiecutter.__package_name_kebab_case }}/.pre-commit-config.yaml
> ci: use pre-commit args

- {{ cookiecutter.__package_name_kebab_case }}/.gitlab-ci.yml
- {{ cookiecutter.__package_name_kebab_case }}/.pre-commit-config.yaml
- {{ cookiecutter.__package_name_kebab_case }}/Dockerfile
- {{ cookiecutter.__package_name_kebab_case }}/README.md
- {{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
> feat: upgrade to Poetry v1.2

- README.md
- {{ cookiecutter.__package_name_kebab_case }}/README.md
- {{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
> docs: improve README

- {{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
> fix: remove Typer's dependency on Pydantic

- {{ cookiecutter.__package_name_kebab_case }}/.gitlab-ci.yml
> fix: fix parallel jobs in GitLab CI pipeline

- .devcontainer/devcontainer.json
- .pre-commit-config.yaml
> feat: add template devcontainer

- {{ cookiecutter.__package_name_kebab_case }}/.devcontainer/devcontainer.json
- {{ cookiecutter.__package_name_kebab_case }}/Dockerfile
> feat: improve Docker build performance

- {{ cookiecutter.__package_name_kebab_case }}/Dockerfile
- {{ cookiecutter.__package_name_kebab_case }}/docker-compose.yml
This PR will persist the zsh command history across Dev Containers with a named Docker volume [1].
Closes #140.
[1] https://code.visualstudio.com/remote/advancedcontainers/persist-bash-history
> feat: persist command history

- {{ cookiecutter.__package_name_kebab_case }}/README.md
Closes https://github.com/radix-ai/poetry-cookiecutter/issues/153.
> docs: make setup OS independent

- README.md
- {{ cookiecutter.__package_name_kebab_case }}/README.md
This PR adds an [Open in Codespaces badge](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/setting-up-your-repository/adding-a-codespaces-badge) in the root README and an [Open in Dev Containers badge](https://code.visualstudio.com/docs/devcontainers/create-dev-container#_add-an-open-in-dev-container-badge) in the project README.
> feat: add open in dev containers badge

- {{ cookiecutter.__package_name_kebab_case }}/.gitlab-ci.yml
- {{ cookiecutter.__package_name_kebab_case }}/Dockerfile
> fix: grant permissions for GitLab CI/CD

- {{ cookiecutter.__package_name_kebab_case }}/Dockerfile
- {{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
Closes https://github.com/radix-ai/poetry-cookiecutter/issues/188.
> feat: loosen version constraints

- hooks/post_gen_project.py
> feat: remove py.typed and Dependabot in simple mode

- {{ cookiecutter.__project_name_kebab_case }}/Dockerfile
Poetry install by default doesn't install a project's extras, this PR fixes that.
> fix: install extras

- {{ cookiecutter.__project_name_kebab_case }}/.devcontainer/devcontainer.json
Some setting values are deprecated and need to be updated.
> chore: update Dev Container settings

- {{ cookiecutter.__project_name_kebab_case }}/Dockerfile
> fix: avoid dubious ownership git warning

- {{ cookiecutter.__project_name_kebab_case }}/.devcontainer/devcontainer.json
See https://marketplace.visualstudio.com/items?itemName=ms-python.mypy-type-checker
> feat: prefer mypy daemon

- {{ cookiecutter.__project_name_kebab_case }}/README.md
> feat: add GitHub Codespaces badge

- README.md
- template/README.md.jinja
- uv.lock
Add the following demo to the README:
https://github.com/user-attachments/assets/28d23137-ebae-47d8-a6e5-11f66abf2a91
> docs: add demo to README

- pyproject.toml
- template/pyproject.toml.jinja
- uv.lock
> feat: select uv as commitizen's version provider

- .github/workflows/test.yml
- template/{% if ci == 'github' %}.github{% endif %}/workflows/test.yml.jinja
- template/{% if ci == 'github' %}.github{% endif %}/workflows/{% if project_type == 'package' %}publish.yml{% endif %}.jinja
- {{ cookiecutter.__project_name_kebab_case }}/.github/workflows/test.yml
Changes:
1. Upgrade `setup-uv` to v6.
2. Upgrade `devcontainers/cli` to v0.76.
> feat: upgrade CI dependencies
