superlinear-ai/substrate

{{ cookiecutter.package_name|slugify }}/pyproject.toml, {{ cookiecutter.package_name|slugify }}/src/{{ cookiecutter.package_name|slugify|replace("-", "_") }}/__init__.py, {{ cookiecutter.package_name|slugify }}/src/{{ cookiecutter.package_name|slugify|replace("-", "_") }}/{% if cookiecutter.with_fastapi_api|int %}api.py{% endif %}
- `coloredlogs` is no longer available by default for Streamlit, but the benefit there isn't as big as with FastAPI.
=> Improve `coloredlogs` installation

{{ cookiecutter.package_name|slugify }}/{% if cookiecutter.continuous_integration == "GitLab" %}.gitlab-ci.yml{% endif %}
This broke on GitLab CI for some reason. The new allowed property is
described on:
https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html#artifactsreportscoverage_report
=> fix: Use `coverage_report` instead of `cobertura`

{{ cookiecutter.package_name|slugify }}/.github/workflows/test.yml, {{ cookiecutter.package_name|slugify }}/.github/workflows/{% if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int %}deploy.yml{% endif %}, {{ cookiecutter.package_name|slugify }}/.github/workflows/{% if not cookiecutter.with_fastapi_api|int and not cookiecutter.with_streamlit_app|int %}publish.yml{% endif %}, {{ cookiecutter.package_name|slugify }}/Dockerfile, {{ cookiecutter.package_name|slugify }}/README.md, {{ cookiecutter.package_name|slugify }}/docker-compose.yml, {{ cookiecutter.package_name|slugify }}/pyproject.toml, {{ cookiecutter.package_name|slugify }}/{% if cookiecutter.continuous_integration == "GitLab" %}.gitlab-ci.yml{% endif %}
- [Docker Compose v2.5.0](https://github.com/docker/compose/releases/tag/v2.5.0) (released 2022-04-29) adds support for build time secrets.
- [Docker Desktop 4.8.0](https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-480) (released 2022-05-06) ships with Docker Compose v2.5.0.
- Before this PR, build time secrets were implemented for the Docker CLI only. For Docker Compose, build time secrets were implemented as environment variables.
- Before this PR, run time secrets were implemented as environment variables.
- After this PR, build and run time secrets are supported for both the Docker CLI as well as Docker Compose.
- This PR also simplifies the one-time setup in a few ways:
- Poetry credentials are now managed in Poetry's `auth.toml`.
- It is no longer needed to configure …
=> feat: use build and run time secrets

README.md
- Remove the `.git` extension, which is no longer necessary
- Gently refer users to `pyenv-virtualenv` as a recommendation to install cruft into
- Move features up top and add cross-platform support as a feature
=> docs: improve root README

{{ cookiecutter.package_name|slugify }}/.devcontainer/devcontainer.json, {{ cookiecutter.package_name|slugify }}/Dockerfile
- [Use an explicit virtual environment to install all Poetry-managed dev and run time dependencies in](https://github.com/python-poetry/poetry/issues/1579#issuecomment-863737675)
- [Automatically activate the virtual environment](https://pythonspeed.com/articles/activate-virtualenv-dockerfile/) in the Docker image
- Removes messages from Poetry or Poe about not activating a virtual environment
- There are now three environments in the image:
- The system environment
- Poetry's virtual environment
- The application's virtual environment
=> feat: use venv to manage app dependencies

{{ cookiecutter.package_name|slugify }}/.devcontainer/devcontainer.json
This PR minimises the `devcontainer.json` and by doing so also fixes the startup warning (specifically, by not explicitly setting the language server to `Pylance` – which is the default anyway):
> The Pylance extension is not installed but the python.languageServer value is set to "Pylance". Would you like to install the Pylance extension to use Pylance, or revert back to Jedi?
=> fix: minimize devcontainer settings

{{ cookiecutter.package_name|slugify }}/README.md, {{ cookiecutter.package_name|slugify }}/docker-compose.yml
=> feat: improve docker compose networking

{{ cookiecutter.package_name|slugify }}/Dockerfile
Changes:
Results for a basic package with FastAPI and Typer:
- `dev` image is now only 447MB (from about 650MB).
- `app` image is now only 210MB (also from about 650MB).
One more optimization could be to copy the virtualenv from the `ci` image to the `app` image. That would mean the `app` image no longer has `poetry` itself, which is another 44MB. However, I think this adds complexity and could also make the image more fragile: I'd have to check but it could be that `poe` depends on `poetry` being available.
=> feat: optimize image size and build speed

{{ cookiecutter.package_name|slugify }}/Dockerfile, {{ cookiecutter.package_name|slugify }}/{% if cookiecutter.continuous_integration == "GitLab" %}.gitlab-ci.yml{% endif %}
Build-essential is still needed on Apple silicon for certain (transitive) dependencies such as ruamel.yaml.
=> fix: add build-essentials to devcontainer

{{ cookiecutter.package_name|slugify }}/.devcontainer/devcontainer.json, {{ cookiecutter.package_name|slugify }}/docker-compose.yml
Problem: SSH keys are no longer automatically loaded when needed with the workaround proposed in https://github.com/microsoft/vscode-remote-release/issues/4024.
Solution:
- Linux and Windows users will have to make sure to [load their SSH keys on the host as the Remote Containers documentation recommends](https://code.visualstudio.com/docs/remote/containers#_using-ssh-keys).
- SSH keys are automatically loaded on macOS by adding `ssh-add --apple-load-keychain` to the `devcontainer.json`'s `initializeCommand`.
=> feat: improve SSH key loading

{{ cookiecutter.package_name|slugify }}/.devcontainer/devcontainer.json, {{ cookiecutter.package_name|slugify }}/Dockerfile, {{ cookiecutter.package_name|slugify }}/README.md, {{ cookiecutter.package_name|slugify }}/docker-compose.yml
Improvements:
1. [x] You can now run `docker compose run --rm dev` to start a Dev Container from the terminal. This is useful if you want to work from within the Dev Container without using VS Code or PyCharm. Also, if you use PyCharm, you will probably need to run the Dev Container alongside it like this to actually run commands like `poetry add` or `git commit` from within the environment.
- `stdin_open: true` is added to the `dev` service to enable (1) to drop you into stdin (equivalent to `docker run -i`).
- `zsh` is now the default command in `docker-compose.yml` so that you drop into `zsh` with `docker compose run`.
2. [x] The host's SSH agent is mounted again, otherwise a Terminal-based Dev Container (1) would not be very useful.
3. [x] Because (1) interferes with VS Code's Dev …
=> feat: better dev containers

{{ cookiecutter.package_name|slugify }}/.github/dependabot.yml
[1] https://github.com/dependabot/dependabot-core/issues/4435
=> feat: improved dependabot updates

{{ cookiecutter.package_name|slugify }}/Dockerfile, {{ cookiecutter.package_name|slugify }}/{% if cookiecutter.continuous_integration == "GitLab" %}.gitlab-ci.yml{% endif %}
- Introduce a `deps` stage: contains Poetry dependencies
- Change the `ci` stage to also include dev dependencies (later only test dependencies)
- Completely skip the build stage if no changes have been made to Docker or Poetry files using `rules:changes`
- Use `--cache-from` + CI image SHA to speed up the `test` and `app` Docker build (`test` gets much faster because we use a cached version of the `dev` stage)
This approach has given me some really nice speedup on GitLab CI:
- We don't even start the build stage if the relevant files haven't changed, and therefore there's no need to spin up `docker-in-docker`, which saves time. This did require moving the hash computation out into a separate stage.
- The `ci` stage contains dev dependencies as well, so `poetry install` in the `test` …
=> feat: Improve Docker caching on GitLab CI

{{ cookiecutter.package_name|slugify }}/.devcontainer/devcontainer.json
[Dev Containers now have a tool-independent specification](https://github.com/devcontainers/cli). This PR puts the VS Code-specific properties in the Dev Container file in a [dedicated section for VS Code customizations](https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_vs-code-specific-properties).
=> feat: upgrade to new devcontainer spec

.github/workflows/test.yml, {{ cookiecutter.package_name|slugify }}/.github/workflows/test.yml, {{ cookiecutter.package_name|slugify }}/.github/workflows/{% if cookiecutter.with_fastapi_api|int or cookiecutter.with_streamlit_app|int %}deploy.yml{% endif %}, {{ cookiecutter.package_name|slugify }}/.github/workflows/{% if not cookiecutter.with_fastapi_api|int and not cookiecutter.with_streamlit_app|int %}publish.yml{% endif %}, {{ cookiecutter.package_name|slugify }}/pyproject.toml
Uses the new [devcontainers/ci](https://github.com/devcontainers/ci) GitHub Action to test the Dev Container directly, instead of creating a local Python environment as we do now.
EDIT: Because of https://github.com/devcontainers/ci/issues/148, we'll use the devcontainers CLI instead.
=> ci: test with devcontainer CLI

{{ cookiecutter.package_name|slugify }}/Dockerfile
=> feat: persist zsh command history

{{ cookiecutter.package_name|slugify }}/.devcontainer/devcontainer.json, {{ cookiecutter.package_name|slugify }}/Dockerfile, {{ cookiecutter.package_name|slugify }}/docker-compose.yml
This PR brings two improvements:
1. After this PR, the Dev Container's `auth.toml` is loaded properly even if you override the docker compose command. Before this PR, if you use a different command then `auth.toml` would not be available in the container.
2. We set a default for `POETRY_AUTH_TOML_PATH` in `docker-compose.yml` so that you can skip setting that variable if you are on macOS. Other environments will still need to set that variable if the project uses a private package repository.
=> feat: improve secrets mounting

{{ cookiecutter.package_name|slugify }}/pyproject.toml
This PR applies `use_exec = true` to serve apps with Poe, see https://github.com/nat-n/poethepoet/issues/47.
=> feat: serve apps with exec

{{ cookiecutter.package_name|slugify }}/pyproject.toml
From [1]:
> The biggest Typer release in a long time 🤯🎉
> 
> Deep integration with [@textualizeio](https://twitter.com/textualizeio) ([@willmcgugan](https://twitter.com/willmcgugan)) Rich 💰🎨
> 
> Still optional, but if you install Rich, or:
> 
> pip install "typer[all]"
> 
> ...your app will shine, by default ✨
> 
> Go get version 0.6.1 (a quick bug fix on top of 0.6.0) 🔖
[1] https://twitter.com/tiangolo/status/1546961217251590145?s=20&t=5Uf1d8_HC0Mf-694QMn7bg
=> feat: upgrade typer with rich

{{ cookiecutter.package_name|slugify }}/.flake8, {{ cookiecutter.package_name|slugify }}/pyproject.toml
Improvements:
1. Move options from `addopts` to dedicated configuration options [1], if available.
2. Remove `junit_family = "xunit2"`, which is the default since pytest v6.1 [2].
3. Add `xfail_strict = true` to make tests that are marked to expect to fail but actually pass, to fail.
4. Add `src` to the `testpaths` so that doctests are automatically executed as well when you run `pytest`. This also allows us to not have to explicitly say we want to run tests in `src` and `tests` when using Coverage.py with `poe lint`.
5. Add color output for flake8 (new since v5.0.0), isort, pytest (especially useful in CI where auto-detection fails).
6. Upgrade from `known_first_party` to `src_paths` in isort.
7. Fix URLs to config documentation.
[1] …
=> feat: improve flake8, isort, and pytest config

{{ cookiecutter.package_name|slugify }}/.github/dependabot.yml
Dependabot already adds a scope to the commit prefix, so no need for us to specify one:
=> ci: remove superfluous Dependabot scope

{{ cookiecutter.package_name|slugify }}/.devcontainer/devcontainer.json, {{ cookiecutter.package_name|slugify }}/.flake8, {{ cookiecutter.package_name|slugify }}/.pre-commit-config.yaml, {{ cookiecutter.package_name|slugify }}/pyproject.toml
Changes:
- Removed `flake8-use-fstring` (and `FS003`) in favour of `pyupgrade`
- Upgrade `pre-commit-hooks` from v4.1.0 to v4.3.0
- Upgrade `flake8` from v4.0.1 to v5.0.4
- Upgrade `safety` from v1.10.3 to v2.1.1 and simplify `poe lint` with it
- Replace `flake8-bandit` with `bandit` (because of https://github.com/tylerwince/flake8-bandit/issues/33)
=> feat: upgrade linters

{{ cookiecutter.__package_name_kebab_case }}/.devcontainer/devcontainer.json, {{ cookiecutter.__package_name_kebab_case }}/Dockerfile, {{ cookiecutter.__package_name_kebab_case }}/README.md, {{ cookiecutter.__package_name_kebab_case }}/docker-compose.yml
Before this PR, Linux support was not great:
1. Within the Dev Container, you are `root`.
2. All files created by you in the Dev Container are therefore owned by `root` in the container.
3. On Linux, files you create within the Dev Container in a (bind-)mounted volume are unfortunately then also owned by `root` on the host system [1]. The result is that you cannot edit those files later on.
This PR brings Linux support to the same level as macOS by introducing a new user that has the same user id and group id as your user on the host machine. This addresses the ownership issue above, and is also better for security as the application won't run as a privileged user [2].
[1] https://github.com/moby/moby/issues/3206
[2] https://pythonspeed.com/articles/root-capabilities-docker-security/
=> feat: add Linux support

{{ cookiecutter.__package_name_kebab_case }}/.devcontainer/devcontainer.json, {{ cookiecutter.__package_name_kebab_case }}/README.md, {{ cookiecutter.__package_name_kebab_case }}/docker-compose.yml
Problem: before this PR, GitHub Codespaces starts up, but is not usable because the `dev` service mounts the host's `~/.gitconfig` and `~/.ssh/known_hosts`, which are not available on GitHub Codespaces and so instead you see them mounted as empty directories in the dev container.
Solution: the solution is to have separate `devcontainer` service in the `docker-compose.yml` that minimally configures the service for a real Dev Container, and then to have a `dev` service that extends the `devcontainer` service and adds additional configuration that is necessary if you run it as a regular container without the Dev Container conveniences (such as .gitconfig, known_hosts, and forwarding the host's SSH agent).
=> feat: support GitHub Codespaces

{{ cookiecutter.__package_name_kebab_case }}/.pre-commit-config.yaml
This PR removes the `python-no-eval` hook because of false positives caused by PyTorch [1].
Closes #126.
[1]  https://github.com/pre-commit/pygrep-hooks/pull/103
=> fix: remove python-no-eval hook

{{ cookiecutter.__package_name_kebab_case }}/Dockerfile
We forgot to adapt the mounting of Docker secrets after improving the build performance with #137. This PR updates secret mounting so that they are mounted in the right location with the right permissions.
=> fix: fix Docker secret mounting

{{ cookiecutter.__package_name_kebab_case }}/Dockerfile
Problem: `/home/app/.cache/pypoetry/` was owned by `root` instead of the `app` user. Probably caused by BuildKit mounting the cache folder with the wrong user.
Solution: create `/home/app/.cache/pypoetry/` and `/home/app/.config/pypoetry/` with the `app` user before letting BuildKit mount any cache folders (or secrets).
=> fix: fix directory permissions

.gitignore, {{ cookiecutter.__package_name_kebab_case }}/.gitignore
Closes https://github.com/radix-ai/poetry-cookiecutter/issues/154.
=> fix: explicitly ignore ruff cache

{{ cookiecutter.__package_name_kebab_case }}/.pre-commit-config.yaml, {{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
Changes:
1. Upgrade Ruff to 0.0.215.
2. Ignore RET504: the idea is to remove unnecessary assignments before the return statement. However, we shouldn't be too strict about this as sometimes you do want to add an assignment for clarity.
3. Mark F401 as unfixable: we don't want to auto remove unused imports if you're importing them for the first time. Ruff will continue to mark unused imports as linting issues though.
=> feat: improve ruff config

{{ cookiecutter.__package_name_kebab_case }}/.pre-commit-config.yaml, {{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
Prevent unassigned variables from getting removed after saving.
=> fix: add ruff ignore F841 to prevent removal of unassigned variables

{{ cookiecutter.__package_name_kebab_case }}/.pre-commit-config.yaml, {{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
ERA001 only applies in strict mode, but when it does it's preferable not to have commented code removed on save.
=> fix: simplify and improve ruff config

{{ cookiecutter.__package_name_kebab_case }}/README.md, {{ cookiecutter.__package_name_kebab_case }}/docker-compose.yml
Update the `auth.toml` location for macOS to align with Poetry v1.2.0 and up [1].
[1] https://python-poetry.org/docs/1.2/configuration
=> fix: update auth.toml location for macOS

{{ cookiecutter.__package_name_kebab_case }}/.devcontainer/devcontainer.json, {{ cookiecutter.__package_name_kebab_case }}/docker-compose.yml
Currently, you cannot use the new [Open in Dev Containers badge](https://github.com/radix-ai/poetry-cookiecutter/pull/165) because the `docker-compose.yml` file tries to mount the current directory, which is not compatible with cloning the repo into a (named) Docker volume first.
To support both use cases (mounting the repo from a local directory, and mounting the repo from a Docker volume), we first expose Dev Container's `localWorkspaceFolder` variable to Docker Compose, and then mount that dynamically [1].
[1] https://stackoverflow.com/questions/60778464/vscode-devcontainer-json-mounts-not-working
=> fix: enable cloning into Docker volume

README.md, {{ cookiecutter.__package_name_kebab_case }}/README.md
VS Code's extension has been renamed, this PR updates Poetry Cookiecutter to reflect that.
=> docs: rename Remote-Containers to Dev Containers

{{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
This PR addresses formatting issues in `pyproject.toml` if you set `cookiecutter.python_version` with a Python version including the patch version, e.g. `3.8.15` instead of `3.8`.
=> fix: allow pinning Python patch version

{{ cookiecutter.__package_name_kebab_case }}/Dockerfile
TLDR: Passing `--no-log-init` to `useradd` prevents an issue where the Docker image size would potentially increase to hundreds of gigabytes when passed a "large" UID or GID. This is apparently a side effect of how `useradd` creates the user fail logs.
The issue is explained in more detail at
https://github.com/docker/docs/issues/4754. The root cause is apparently combination of the following:
1. `useradd` by default allocates space for the faillog and lastlog for "all" users: https://unix.stackexchange.com/q/529827. If you pass it a high UID, e.g. 414053617, it will reserve space for all those 414053617 user logs, which amounts to more than 260GB.
2. The first bullet wouldn't be a problem if Docker would recognize the sparse file and compress it efficiently. However, there is an …
=> bugfix: Avoid exploding Docker image size

{{ cookiecutter.__package_name_kebab_case }}/.pre-commit-config.yaml
This is a workaround for #184 until Ruff implements `--extend-fixable` [1].
[1] https://github.com/charliermarsh/ruff/discussions/4272
=> fix: enable all commit-time autofixes

{{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
Hotfix that solves:
- Dependency conflict between safety and black (https://github.com/pyupio/safety/issues/455) by disallowing 2.3.5.
- Dependency conflict with commitizen by constraining Python to <4.0.
=> fix: solve conflict between safety and black

README.md, {{ cookiecutter.__package_name_kebab_case }}/.pre-commit-config.yaml, {{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
- Removes `absolufy-imports` as [the TID rules include an autofix for this](https://beta.ruff.rs/docs/rules/#flake8-tidy-imports-tid) (closes #150).
- Uses the new `--extend-fixable` to add fixable rules in `poe lint`.
- Adds many new rules to both simple and strict mode.
- Updated configuration of some rules.
=> feat: extend Ruff rules and config

{{ cookiecutter.__package_name_kebab_case }}/README.md, {{ cookiecutter.__package_name_kebab_case }}/docker-compose.yml
The path to Poetry's `auth.toml` was changed again [1].
[1] https://github.com/python-poetry/poetry/blob/master/src/poetry/locations.py#L24-L30
=> fix: revert auth.toml path on macOS

.github/workflows/test.yml, {{ cookiecutter.__package_name_kebab_case }}/.dockerignore, {{ cookiecutter.__package_name_kebab_case }}/.github/workflows/deploy.yml, {{ cookiecutter.__package_name_kebab_case }}/.github/workflows/publish.yml, {{ cookiecutter.__package_name_kebab_case }}/.github/workflows/test.yml, {{ cookiecutter.__package_name_kebab_case }}/.gitlab-ci.yml, {{ cookiecutter.__package_name_kebab_case }}/Dockerfile, {{ cookiecutter.__package_name_kebab_case }}/README.md
=> feat: update GitLab CI/CD to use the Dev Container CLI

{{ cookiecutter.__package_name_kebab_case }}/.pre-commit-config.yaml
See PR #207 for the reason behind removing this hook.
=> chore: remove `no-commit-to-branch` hook

{{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
In 0.2.0, https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md#020, config entries related to linting settings have been moved. This commit moves the deprecated entries under the right header in `pyproject.toml`.
=> chore: fix deprecated ruff config

{{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
This PR adds two changes:
1. Makes PyPI the default package source when adding a private package repo. This is needed because [Poetry warns that this will no longer be the case in a future release](https://python-poetry.org/docs/repositories/#default-package-source).
2. [Makes the private package repo an explicit source](https://python-poetry.org/docs/repositories/#explicit-package-sources), so that you need to mark your dependency with `source = "my-private-package-repo"` to install from the private package repo.
=> feat: make private package repos explicit

{{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
Using Poetry as the version provider source will specifically get and set the version using the `tool.poetry.version` field in `pyproject.toml`, as described [here](https://commitizen-tools.github.io/commitizen/config/#version-providers).
This has two advantages:
1. We only have to keep track of the project version in one place in `pyproject.toml`.
2. We avoid bugs that can result from the "naive" way that `cz bump` works when using `version_files` instead of `version_provider`. When bumping the version, it will replace all instances of the current version string in `pyproject.toml` with the new version string. This can cause bugs when certain dependencies coincidentally have a version constraint which contains the current version string as a substring. When this happens, it results in an …
=> fix: use Poetry as Commitizen version provider

{{ cookiecutter.__package_name_kebab_case }}/pyproject.toml
Changes:
- Replace PGH001 with S307 because [the former has been deprecated in favour of the latter](https://github.com/astral-sh/ruff/issues/7283)
- Ignore D203 [because it is in conflict with D211](https://github.com/PyCQA/pydocstyle/issues/141)
- Ignore D213 [because it is in conflict with D212](https://github.com/PyCQA/pydocstyle/issues/475)
- Replace PLC, PLE, PLR, and PLW with PL
- Add [Q](https://docs.astral.sh/ruff/rules/#flake8-quotes-q)
=> chore: update ruff rules

{{ cookiecutter.__project_name_kebab_case }}/pyproject.toml
It's generally useful to be have ipywidgets when creating notebooks in VS Code.
=> feat: add ipywidgets to dev dependencies

{{ cookiecutter.__project_name_kebab_case }}/pyproject.toml
We shouldn't assume that the runtime dependencies are for an application. This PR loosens all runtime dependencies.
=> fix: loosen runtime dependency specification

.github/workflows/test.yml, {{ cookiecutter.__project_name_kebab_case }}/.github/dependabot.yml, {{ cookiecutter.__project_name_kebab_case }}/.github/workflows/publish.yml, {{ cookiecutter.__project_name_kebab_case }}/.github/workflows/test.yml
Before this PR: the Dependabot configuration is suboptimal because it doesn't differentiate well between applications and packages, and because it doesn't group updates to reduce the number of PRs.
After this PR:
- For Python applications and packages:
- Every month, Dependabot will create *a single* PR for all direct development dependency updates. This PR will bump the minimum version of these dependencies in `pyproject.toml`.
- ~~Every month, Dependabot will create *a single* PR for all transitive dependency updates (of both production & development dependencies). This PR only updates the lockfile.~~
- For Python applications:
- Every month, Dependabot will create *a single*  PR for all direct production dependency updates. This PR will bump the minimum version of these dependencies in …
=> feat: optimize Dependabot config

README.md
Improve `cruft update` instructions by recommending to use `--cookiecutter-input` so that users can verify the existing template parameters and, importantly, set any new template parameters if there are any (cf. https://github.com/cruft/cruft/issues/232#issuecomment-2068932691).
=> docs: improve cruft update instructions

{{ cookiecutter.__project_name_kebab_case }}/pyproject.toml
Ruff has deprecated this feature and has improved support for unused imports built-in now.
=> fix: remove deprecated ruff imports feature

.github/workflows/test.yml, {{ cookiecutter.__project_name_kebab_case }}/pyproject.toml
Poetry Cookiecutter already included `ipykernel` and `ipywidgets` for Jupyter notebook support in VS Code. This PR adds `ipython` to the dev dependencies to make that available in the terminal as well.
EDIT: Because ipython requires Python 3.10 or higher, this PR increases the minimum Python version in addition to adding ipython to the dev dependencies.
=> feat: increase minimum Python version to 3.10

{{ cookiecutter.__project_name_kebab_case }}/.devcontainer/devcontainer.json
The `warn` ruff log level we use in strict mode has been renamed to `warning`. This PR updates the setting to match the new value.
=> fix: update ruff log level

{{ cookiecutter.__project_name_kebab_case }}/pyproject.toml
The earlier addition of `ipython = ">=8.23.0"` conflicts with commitizen and prevents the Docker image to build successfully.
- `commitizen` requires `questionary (>=2.0,<3.0)`.
- `questionary (2.0.0 and 2.0.1)` depend on `prompt_toolkit (>=2.0,<=3.0.36)`.
- `ipython (>=8.23.0)` depends on `prompt_toolkit (>=3.0.41,<3.1.0)`.
**Conflict:** `prompt_toolkit (>=3.0.41,<3.1.0)` required by `ipython (>=8.23.0)` is incompatible with `prompt_toolkit (<=3.0.36)` required by `questionary` (and thus `commitizen`).
I found that `ipython` version  `>=8.18.0` is compatible with commitizen.
=> fix: Conflicting dependencies between ipython and commitizen

{{ cookiecutter.__project_name_kebab_case }}/Dockerfile
Docker appears to balk at the inconsistent casing of `FROM ... AS` in the `Dockerfile`, and this PR fixes that.
=> fix: fix casing of FROM AS in Dockerfile

.devcontainer/devcontainer.json, {{ cookiecutter.__project_name_kebab_case }}/.devcontainer/devcontainer.json
Add Microsoft's Docker VS Code extension by default so that we can avoid VS Code nagging you to install it on startup.
=> feat: add Docker VS Code extension

.github/workflows/test.yml, {{ cookiecutter.__project_name_kebab_case }}/.github/workflows/test.yml, {{ cookiecutter.__project_name_kebab_case }}/.gitlab-ci.yml
Changes:
1. Expand test matrix to include Python 3.11 and 3.13.
2. Upgrade all CI dependencies to their latest versions.
=> ci: expand test matrix and upgrade steps

{{ cookiecutter.__project_name_kebab_case }}/pyproject.toml
Safety is no longer free to use, unfortunately.
=> fix: remove safety

.gitignore, {{ cookiecutter.__project_name_kebab_case }}/.gitignore
[Mise](https://github.com/jdx/mise) is an alternative for [pyenv](https://github.com/pyenv/pyenv) + [direnv](https://github.com/direnv/direnv), and can also manage other tools.
=> feat: add support for mise

{{ cookiecutter.__project_name_kebab_case }}/pyproject.toml
With the upgrade to Poetry v2.0 in #266, the project's version number is now maintained under the `[project]` section instead of the `[tool.poetry]` section. This PR updates Commitizen's configuration so that it manages the version at the new location.
=> fix: configure commitizen to use PEP 621

{{ cookiecutter.__project_name_kebab_case }}/Dockerfile
This PR fixes this Docker warning:
```
LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format
```
=> fix: use new `ENV key=value` format in Dockerfile

.devcontainer/devcontainer.json, pyproject.toml, template/.devcontainer/devcontainer.json.jinja, template/pyproject.toml.jinja, {{ cookiecutter.__project_name_kebab_case }}/pyproject.toml
After bumping the version with `cz bump`, uv's lock file is out of sync with `pyproject.toml`. [Until Commitizen adds support for uv](https://github.com/commitizen-tools/commitizen/issues/1349), this PR adds `uv lock --offline` as a [pre bump hook](https://commitizen-tools.github.io/commitizen/commands/bump/#pre_bump_hooks) (which runs after updating the version but before comitting and tagging) to synchronize `uv.lock` and `pyproject.toml`.
=> fix: relock before cz bump

README.md, template/README.md.jinja
Changes:
1. Project update: exclude `src/` and `tests/` when updating since we only provide an initial scaffolding there that is not intended to be updated.
2. Migration from Poetry Cookiecutter: remove `.cruft.json` as we no longer need it.
=> docs: improve update and migrate commands

template/{% if ci == 'github' %}.github{% endif %}/workflows/test.yml.jinja, {{ cookiecutter.__project_name_kebab_case }}/.github/workflows/test.yml
Instead of setting environment variables inline in our GitHub Actions workflows, this PR lists them so they're easier to read and extend.
=> feat: list environment variables in workflow definition

template/.devcontainer/devcontainer.json.jinja, template/pyproject.toml.jinja
Changes:
1. Make the local environment variables `PYTHON_VERSION` and `RESOLUTION_STRATEGY` available in the container for the `postStartCommand`.
2. Set [Poe the Poet's executor type](https://poethepoet.natn.io/global_options.html#change-the-executor-type) to `simple`. Otherwise, it seemingly reapplies `uv sync` before running a task (related: https://github.com/nat-n/poethepoet/pull/271).
=> fix: fix resolution strategy selection

template/.gitignore, template/.pre-commit-config.yaml.jinja
Changes:
1. Remove `uv lock --check` from the pre-commit hooks for packages, since these will be tested with various resolution strategies.
2. Add `uv.lock` to `.gitignore` to avoid committing the lock file. The only reason to keep it for package development is perhaps to save some time to solve the environment, but since uv is so fast even that isn't really an argument anymore.
=> fix: git ignore uv.lock for packages

template/docker-compose.yml.jinja, template/{% if ci == 'github' %}.github{% endif %}/workflows/{% if project_type == 'package' %}publish.yml{% endif %}.jinja
Changes:
1. Simplify the publishing workflow to use the new [Trusted Publisher feature](https://docs.pypi.org/trusted-publishers/adding-a-publisher/). This means you no longer need to create or set a publish token to publish from GitHub Actions.
2. Fix the `runs-on` field and instead install uv, which is not a valid value and [caused the release of Conformal Tights to hang](https://github.com/superlinear-ai/conformal-tights/actions/runs/13792977495).
3. Simplify `docker-compose.yml` by removing the `UV_PUBLISH_TOKEN` unless the project is configured to publish a package without GitHub Actions.
=> feat: simplify publishing to PyPI from GitHub Actions

template/docker-compose.yml.jinja, template/{% if ci == 'github' %}.github{% endif %}/workflows/{% if project_type == 'package' %}publish.yml{% endif %}.jinja
Changes:
1. Add missing `id-token: write` permission that is necessary for Trusted Publishing [1].
2. Remove the `UV_PUBLISH_TOKEN` altogether since Trusted Publishing is available for several sources, including GitLab.
[1] https://docs.pypi.org/trusted-publishers/using-a-publisher/
=> fix: add missing permission for trusted publishing

template/pyproject.toml.jinja
Changes:
1. Configure a modern build system based on [Hatchling v1.26](https://hatch.pypa.io/dev/history/hatchling/), which adds support for core metadata v2.4.
2. Remove the `package = true` uv setting, since it's not necessary if you specify a build system:
> While uv usually uses the declaration of a [build system](https://docs.astral.sh/uv/concepts/projects/config/#build-systems) to determine if a project should be packaged, uv also allows overriding this behavior with the [tool.uv.package](https://docs.astral.sh/uv/reference/settings/#package) setting.
This is both a fix and a feature: uv's default build system is apparently still setuptools, which does not support some of the more modern core metadata features such as license-file(s). The missing feature can cause publishing to …
=> feat: upgrade to a more modern build system

copier.yml
We use a simple list to choose the `project_type` (either `app` or `package`). This PR does the same for `typing`.
=> style: use consistent choices format

README.md
Reposition the MkDocs section to the Usage section in the README.
=> docs: reposition MkDocs section in README
